export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SCROLL_SCREEN = 'SET_SCROLL_SCREEN';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';
export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
