fastlane_version '2.28.3'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test" , project_dir: 'android/')
  end

  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end

  #desc "Submit a new Beta Build to Crashlytics Beta"
  #lane :beta do
   # gradle(task: "assembleRelease" , project_dir: 'android/')
    #crashlytics
    
    # sh "your_script.sh"
    # You can also use other beta testing services here
  #end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease" , project_dir: 'android/')
    upload_to_play_store
  end
end


platform :ios do
   # iOS Lanes
end
