fastlane_version '2.28.3'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics
    
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store
  end
end


platform :ios do
   # iOS Lanes
end

platform :android do
  # Android Lanes
end
